<!DOCTYPE html><html><head><title>https://blog.gepuro.net/posts/when_using_sqlite_3_from_python_i_get_an_error_sqlite3operationalerror/</title><link rel="canonical" href="https://blog.gepuro.net/posts/when_using_sqlite_3_from_python_i_get_an_error_sqlite3operationalerror/"/><meta name="robots" content="noindex"><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="refresh" content="0; url=https://blog.gepuro.net/posts/when_using_sqlite_3_from_python_i_get_an_error_sqlite3operationalerror/" /></head></html>